apiVersion: apps/v1
kind: Deployment
metadata:
  name: prover-rpcd
spec:
  replicas: 1
  selector:
    matchLabels:
      run: prover-rpcd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: prover-rpcd
    spec:
      tolerations:
      - key: "provers"
        operator: "Exists"
        effect: "NoSchedule"
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
           - labelSelector:
               matchExpressions:
               - key: run
                 operator: In
                 values:
                 - prover-rpcd
             topologyKey: "prover"
      containers:
        - name: prover-rpcd
          image: public.ecr.aws/s1x7c1c0/prover:latest
          env:
            - name: BIND
              value: '[::]:8545'
          resources:
            limits:
              cpu: "1.5"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: .5Gi
      restartPolicy: Always
