apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: coordinator
  name: coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: coordinator
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: coordinator
    spec:
      containers:
        - env:
            - name: DUMMY_PROVER
              value: "1"
            - name: ENABLE_FAUCET
              value: "1"
            - name: L1_BRIDGE
              value: 0x936a70c0b28532aa22240dce21f89a8399d6ac60
            - name: L1_PRIV
              valueFrom:
                secretKeyRef:
                  name: leader-testnet-geth-secrets
                  key: miner_priv_key
            - name: L1_RPC_URL
              value: http://l1-testnet-geth:8545
            - name: L2_RPC_URL
              value: http://leader-testnet-geth:8545
            - name: LISTEN
              value: '[::]:8545'
            - name: PARAMS_PATH
              value: /host/params
            - name: PROVER_RPCD_URL
              value: http://prover-rpcd:8545
            - name: RPC_SERVER_NODES
              value: server-testnet-geth:8545
          image: ghcr.io/privacy-scaling-explorations/zkevm-chain/coordinator:latest
          #image: public.ecr.aws/s1x7c1c0/coordinator:latest
          name: coordinator
          resources: {}
          volumeMounts:
            - mountPath: /host
              name: coordinator-efs
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: coordinator-efs
          persistentVolumeClaim:
            claimName: efs-claim
            readOnly: true
status: {}
