apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: server-testnet-geth
  name: server-testnet-geth
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: server-testnet-geth
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: server-testnet-geth
    spec:
      containers:
        - args:
            - -c
            - geth init /host/l2-genesis-generated.json && geth console --exec admin.addTrustedPeer\(\"$BOOTNODE\"\) && exec geth --gcmode archive --syncmode full --http --http.addr "[::]" --http.port 8545 --http.api eth,net,web3,debug --networkid 99 --bootnodes $BOOTNODE
          command:
            - /bin/sh
          env:
            - name: BOOTNODE
              value: enode://f28f5a7706e5aec836f3136feb7d5e7264a7f0da04ac4984f0ff2421ee1dd2b135894cf0d4f5ff8c412442b95b9bb0780a9c8a8c64de2d4a8c458586fdb20829@leader-testnet-geth:30303
          image: ghcr.io/privacy-scaling-explorations/go-ethereum:latest
          name: server-testnet-geth
          resources: {}
          volumeMounts:
            - mountPath: /host
              name: persistent-storage-efs
      restartPolicy: Always
      volumes:
        - name: persistent-storage-efs
          persistentVolumeClaim:
            claimName: efs-claim
status: {}
