apiVersion: v1
kind: Service
metadata:
  name: leader-testnet-geth
spec:
  clusterIP: None
  ports:
    - name: "30303"
      port: 30303
      targetPort: 30303
    - name: "8545"
      port: 8545
  selector:
    run: leader-testnet-geth
