apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: leader-testnet-geth
spec:
  selector:
    matchLabels:
      run: leader-testnet-geth
  serviceName: leader-testnet-geth
  replicas: 1
  template:
    metadata:
      labels:
        run: leader-testnet-geth
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: leader-testnet-geth
        image: public.ecr.aws/s1x7c1c0/geth:latest
        args: ["--networkid", "99", "--nodiscover", "--gcmode", "archive", "--unlock", "$(MINER_ADDRESS)", "--password", "/dev/null", "--allow-insecure-unlock", "--miner.gaslimit", "300000", "--http", "--http.addr", "[::]", "--http.port",  "8545", "--http.corsdomain=*", "--http.vhosts=*", "--http.api", "eth,net,web3,txpool,miner,debug", "--nodekeyhex", "abebb96d7d9bbc99730439f230afd0008c0e0cb93eafb6874fecb256572252a4"]
        env:
        - name: MINER_PRIV_KEY
          valueFrom:
            secretKeyRef:
              name: leader-testnet-geth-secrets
              key: miner_priv_key
        - name: MINER_ADDRESS
          valueFrom:
            secretKeyRef:
              name: leader-testnet-geth-secrets
              key: miner_address
        - name: BOOTNODE
          value: enode://61f076e9af396ecb5a0a8fb1a2c17491c3514f2abea0c228a3fcee49395339df2008fe201b37c7c0a565b775c5f8f5389b0b3de1701dc532c951a094af841cac@bootnode:30303
        - name: GENESIS
          value: l2-testnet
        volumeMounts:
        - name: leader-testnet-geth
          mountPath: /root
  volumeClaimTemplates:
  - metadata:
      name: leader-testnet-geth
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 15Gi
