apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bootnode
spec:
  selector:
    matchLabels:
      run: bootnode
  serviceName: bootnode
  replicas: 1
  template:
    metadata:
      labels:
        run: bootnode
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: bootnode
        image: public.ecr.aws/s1x7c1c0/geth:latest
        ports:
          - containerPort: 30303
        args: ["--networkid", "99", "--syncmode", "full", "--nodiscover", "--gcmode", "archive", "--light.serve", "100", "--light.nosyncserve", "--nodekeyhex", "be6e66a76b664af9debbe2f4b3b9f21257fcce34412e10dfe383aabca9b4a9c0"]
        env:
        - name: MINER_ADDRESS
          valueFrom:
            secretKeyRef:
              name: leader-testnet-geth-secrets
              key: miner_address
        - name: BOOTNODE
          value: enode://f28f5a7706e5aec836f3136feb7d5e7264a7f0da04ac4984f0ff2421ee1dd2b135894cf0d4f5ff8c412442b95b9bb0780a9c8a8c64de2d4a8c458586fdb20829@leader-testnet-geth:30303
        - name: GENESIS
          value: l2-testnet
        volumeMounts:
        - name: bootnode
          mountPath: /root
  volumeClaimTemplates:
  - metadata:
      name: bootnode
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 15Gi
