apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: web=public.ecr.aws/s1x7c1c0/web:latest
spec:
  project: default
  source:
    repoURL: https://github.com/ntampakas/k8s-zc-argocd.git
    targetRevision: HEAD
    path: zkevm-chain/services/web
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: false
