apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      run: web
  strategy: {}
  template:
    metadata:
      labels:
        run: web
    spec:
      containers:
        - name: web
          image: public.ecr.aws/s1x7c1c0/web:latest
          ports:
            - containerPort: 8000
      restartPolicy: Always
