apiVersion: v1
kind: Pod
metadata:
  name: efs-pod
spec:
  containers:
  - name: efs-pod
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 1; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /host
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-claim
