apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: l1-testnet-geth
  name: l1-testnet-geth
spec:
  selector:
    matchLabels:
      io.kompose.service: l1-testnet-geth
  serviceName: l1-testnet-geth
  replicas: 1
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: l1-testnet-geth
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: l1-testnet-geth
        image: public.ecr.aws/s1x7c1c0/geth:latest
        args: ["--networkid", "98", "--unlock", "$(MINER_ADDRESS)", "--password", "/dev/null", "--allow-insecure-unlock", "--nodiscover", "--miner.gaslimit", "10000000", "--mine", "--http", "--http.addr", "[::]", "--http.port", "8545", "--http.corsdomain=*", "--http.vhosts=*", "--http.api eth,net,web3,debug"]
        env:
        - name: MINER_PRIV_KEY
          valueFrom:
            secretKeyRef:
              name: leader-testnet-geth-secrets
              key: miner_priv_key
        - name: MINER_ADDRESS
          valueFrom:
            secretKeyRef:
              name: leader-testnet-geth-secrets
              key: miner_address
        - name: GENESIS
          value: l1-testnet
        volumeMounts:
        - name: l1-testnet-geth
          mountPath: /root
  volumeClaimTemplates:
  - metadata:
      name: l1-testnet-geth
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 5Gi
