apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: l1-testnet-geth
  name: l1-testnet-geth
spec:
  selector:
    matchLabels:
      io.kompose.service: l1-testnet-geth
  serviceName: l1-testnet-geth
  replicas: 1
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: l1-testnet-geth
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: l1-testnet-geth
        image: ghcr.io/privacy-scaling-explorations/go-ethereum:latest
        command: ["/host/init.sh"]
        args: ["/host/l1-genesis-template.json", "/root/genesis.json", "--networkid", "98", "--unlock", "$(MINER_ADDRESS)", "--password", "/dev/null", "--miner.gaslimit", "10000000", "--mine"]
        env:
        - name: MINER_PRIV_KEY
          valueFrom:
            secretKeyRef:
              name: leader-testnet-geth-secrets
              key: miner_priv_key
        - name: MINER_ADDRESS
          valueFrom:
            secretKeyRef:
              name: leader-testnet-geth-secrets
              key: miner_address
        volumeMounts:
        - name: l1-testnet-geth
          mountPath: /root
        - name: efs-storage
          mountPath: /host
      volumes:
      - name: efs-storage
        persistentVolumeClaim:
          claimName: efs-claim
  volumeClaimTemplates:
  - metadata:
      name: l1-testnet-geth
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 5Gi
