apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      run: coordinator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: coordinator
    spec:
      containers:
        - name: coordinator
          image: public.ecr.aws/s1x7c1c0/coordinator:latest
          env:
            - name: LISTEN
              value: '[::]:8545'
            - name: RPC_SERVER_NODES
              value: server-testnet-geth:8545
            - name: L2_RPC_URL
              value: http://leader-testnet-geth:8545
            - name: L1_RPC_URL
              value: http://l1-testnet-geth:8545
            - name: L1_BRIDGE
              value: 0x936a70c0b28532aa22240dce21f89a8399d6ac60
            - name: L1_PRIV
              valueFrom:
                secretKeyRef:
                  name: leader-testnet-geth-secrets
                  key: miner_priv_key
            - name: PROVER_RPCD_URL
              value: http://prover-rpcd:8545
            #- name: DUMMY_PROVER
            #  value: ${DUMMY_PROVER:-1}
            - name: ENABLE_FAUCET
              value: "1"
            - name: PARAMS_PATH
              value: ${PARAMS_PATH:-/testnet/19.bin}
      restartPolicy: Always
