apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coordinator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ntampakas/k8s-zc-argocd.git
    targetRevision: HEAD
    path: zkevm-chain/services/coordinator
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: false
